### ISSUE TITLE
A question about normalize_compute_shape

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#1030]
what is the meaning of normalize_compute_shape? what is the difference between compute_shape and not normalize_compute_shape?

**Comment by kahmed10** [comment]
normalize_compute_shape is used when operators have inputs or attributes that would otherwise go out of bounds (usually negative, meaning iterate backwards in onnx). You can see an example in the [slice](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/src/include/migraphx/op/slice.hpp) operator.
