### ISSUE TITLE
Converting GPU resident torch.Tensor to/from migraphx.argument without going through CPU

### ISSUE THREAD

**Issue by nrsatish** [ROCmSoftwarePlatform/AMDMIGraphX#1031]
Is there a way for a PyTorch tensor that is already GPU resident to be converted to a migraphx argument without using tensor.cpu().numpy() which needs a GPU->CPU transfer and back when run is called. Similarly, can the resulting output argument of the model be converted to a torch.Tensor for further use without using numpy (which also requires a GPU->CPU transfer)?

**Comment by kahmed10** [comment]
Is this to execute a portion of a pytorch model using MIGraphX?

**Comment by nrsatish** [comment]
Yes, that’s the goal.

**Comment by kahmed10** [comment]
The memory transfers from device to host and vice versa are done in [hip.cpp](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/src/targets/gpu/hip.cpp). That would need to be modified so that we don't have to perform the transfer if the memory already exists on the GPU.

**Comment by pfultz2** [comment]
Are you using the python API or the C++ API? I assume `tensor.cpu().numpy() ` is python.

In python, you can set the `offload_copy` to false when compiling(with [migraphx.compile](https://rocmsoftwareplatform.github.io/AMDMIGraphX/doc/html/reference/py.html#migraphx.compile)) so it will not copy tensors from the cpu to the gpu. All tensors will need to be on the GPU, and the results will be on the GPU as well. You will also need some synchronization before reading the results.

MIGraphX uses python's [buffer protocol](https://docs.python.org/3/c-api/buffer.html#bufferobjects) to create `migraphx.argument` inputs. Python's classes such as [`bytes`](https://docs.python.org/3/library/stdtypes.html#bytes), [`bytearray`](https://docs.python.org/3/library/stdtypes.html#bytearray), and [`array.array`](https://docs.python.org/3/library/array.html#array.array) as well as numpy arrays support the buffer protocol, which is why they can be passes directly to migraphx. I dont know if `torch.Tensor` supports python's buffer protocol or not. Perhaps, something like [`memoryview`](https://docs.python.org/3/library/stdtypes.html#memoryview) might be needed.

**Comment by nrsatish** [comment]
What happens in TensorRT seems to be that the torch.Tensor.data_ptr() which is basically a pointer to GPU memory [https://pytorch.org/docs/stable/generated/torch.Tensor.data_ptr.html] is passed into the execute_async() function of TensorRT [https://github.com/NVIDIA/TensorRT/blob/96e23978cd6e4a8fe869696d3d8ec2b47120629b/python/src/infer/pyPlugin.cpp#L68] for which probably code is written in C++ to handle it.

**Comment by qianqing13579** [comment]
@nrsatish, @kahmed10 , I have a solution. First,a function need to be added in migraphx_py.cpp.
```
m.def("gpudata_to_argument",
        [](const migraphx::shape shape,int64_t address)
        {
            return migraphx::argument(shape, (void *)address);
        },
        py::arg("shape"),
        py::arg("address")
        );
```

and when you want to convert gpu tensor to argument,you can write like this:
```
# create a gpu tensor
input_tensor=torch.from_numpy(image).to(torch.device("cuda"))

# use gpu tensor without using tensor.cpu().numpy()
arg=migraphx.gpudata_to_argument(shape=s,address=input_tensor.data_ptr())
```

**Comment by kahmed10** [comment]
@qianqing13579 does this solution need synchronization before reading the GPU result?

**Comment by qianqing13579** [comment]
@kahmed10 ,yes. The syn_device pass needs to be modified modified.The new code is as follows:
```
#include <migraphx/gpu/sync_device.hpp>
#include <migraphx/program.hpp>
#include <migraphx/instruction.hpp>
#include <migraphx/make_op.hpp>
#include <migraphx/iterator_for.hpp>

namespace migraphx {
inline namespace MIGRAPHX_INLINE_NS {
namespace gpu {

void sync_device::apply(module& p) const
{
    auto last = std::prev(p.end());
    if(last->name() == "@return")
    {
        auto inputs = last->inputs();
        auto sync_in = p.insert_instruction(last, make_op("hip::sync_stream"), inputs);
        if(not inputs.empty())
        {
            p.replace_instruction(inputs.front(), sync_in);
        }
    }
}

} // namespace gpu
} // namespace MIGRAPHX_INLINE_NS
} // namespace migraphx

```

the difference between them:
![image](https://user-images.githubusercontent.com/8730200/168995820-c4708266-eb50-46a0-8348-00e6507cbba3.png)

**Comment by causten** [comment]
Choosing different route, will use a Torch MIGraphX solution
