### ISSUE TITLE
Store Tuning information with the MXR

### ISSUE THREAD

**Issue by causten** [ROCmSoftwarePlatform/AMDMIGraphX#1303]
Goal
Save tuning information and/or code objects with a model (MXR file) so that it can move to other physical servers and still have the tuning information.  If an MXR file has tuning information it should by default use it.

Design Ideas
- Invoke CK operations
- Save traditional MIOpen tuning plans 
- Initiate MIOpen tuning (and then capture it) 
- Limit tuning time (time budgeting) 
- Need to consider version of miopen vs migrapx mismatches
- Need to consider hardware model information.  Should actual MXR file have multiple HW/rocm versions ?  Could you replace /upgrade existing information already in the model
- Dump meta data labels (rocm version, hardware version, what things it has tuned)
- Consider remove tuning information by user request

Notes
- Currently MIGX uses an Immediate Mode [API](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/perfdatabase.html) from MIOpen
- MIOpen team has a new API to facilitate this call Find 2.0

Invocation (user perspective)
- use a new flag (--tune) to indicate to tune via the migraphx-driver command

Phases of development
- get it to work on a single model/rocm version first 
- support different hardware in same MXR
- support different version in MXR

Test Considerations
- Test incompatible execution such as MXR data contains gfx90A data but run on gfx908
- Tune multiple times

**Comment by umangyadav** [comment]
First part : 

Update interface with MIOpen to use the new Find-2.0 API instead of Immediate mode. 

- MIOpen itself provides API to store and load miOpenSolutions struct. We can use that to save tunings information during our `Find()`  call. Load the same solution struct during the `Finalize` call. 
- Add additional fields into `miOpenConvolutionOp` object in MIGraphX to aid in serialization of `miOpenSolution` struct. 
- Store `miOpenSolution` struct using binary value type during serialization. 
-  Refactor or apply same sort of changes for quant_convolution. 
- TBD :  Backwards compatibility with a flag in MIGraphX to disable Find2.0.

Second part : 
Error check for  incompatibility : 
- TBD: Does MIOpen itself throws an error if there is mismatch in rocm version or miopen version or target arch mismatch ? If it does then perhaps no need for doing compatibility check through MIGraphX.
