### ISSUE TITLE
Support RNN operators RNN, LSTM, GRU in pytorch...

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#138]
Pytorch contains RNN operators RNN, LSTM, and GRU. These operators heavily uses dynamic shape, and operators like torch.nn.LSTM need a lot of of onnx operator to representation them as in the attached file. One main feature we need is to support dynamic shape in some degree in MIGraphX (covered in issue#59). 

[rnn_lstm41.log](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/2672629/rnn_lstm41.log)
[rnn_lstm40.log](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/2672630/rnn_lstm40.log)

**Comment by mvermeulen** [comment]
A few questions:

1. Looking at PyTorch 0.4.0 documentation (https://pytorch.org/docs/0.4.0/nn.html), I see that RNN, LSTM and GRU were present in that release as well. Were they also implemented using dynamic shapes in that release?

2. My best understanding of RNN/LSTM/GRU "nodes" is as a shorthand for defining a recurrence relationship as well as some internal storage.  So that brings to mind, at what point such "lowering" occurs to the lower level operations as well as who/where the underlying storage gets allocated.  I can see a few different points on the spectrum of lowering RNN/LSTM/GRU operations...
a. Our original "char rnn" example was an example of a "recurrent neural network", but didn't actually specifically use RNN nodes.  So in that case, our python program has the "hidden" parameter allocated and passed at each iteration...
b. At the opposite end of the spectrum, it seems like the Nvidia cuDNN library added specific cuDNN library calls (https://devblogs.nvidia.com/optimizing-recurrent-neural-networks-cudnn-5/) that are documented in their API.  In this case, it seems like one might carry such operations forward all the way to the library level - https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html/#features-of-rnn-functions
c. It looks like the *.log snippets you've provided have done some lowering, but also attach a "LSTM scope" tag, so one can still keep track of both underlying pieces but also that they came from a particular API
d. In contrast, when I see the ONNX specification for the RNN operator - https://github.com/onnx/onnx/blob/master/docs/Operators.md#RNN  It looks like these particular operators haven't yet been lowered and even refer to exporting this to a cuDNN layer...

So based on question 2, I can potentially see two somewhat different approaches, both of which might need some support somewhere else:
1. The pytorch.nn interface layer provides a "rnn" operation, this gets lowered to lower level stuff as part of the ONNX that gets exported.  This seems to be reflected in the logfiles you listed, in which case I also have a question if the dynamic pieces are still there when one exports from PyTorch 0.4.0.
2. A pytorch program does not actually lower this, but instead creates an ONNX file that uses the RNN operator that is defined in the ONNX specification.  As MIGraphX, we optimize graphs with such nodes, but then either need to do some type of lowering ourselves - or need to keep them as RNN/LSTM type nodes to eventually turn into library calls.  This would need some support in MIOpen similar to the cuDNN routines provided elsewhere.

Thoughts @scxiao @pfultz2 ?

**Comment by mvermeulen** [comment]
Operators added in release 0.2.  Closing this issue.
