### ISSUE TITLE
bug in driver argument parser

### ISSUE THREAD

**Issue by kahmed10** [ROCmSoftwarePlatform/AMDMIGraphX#1809]
Although this isn't a driver read command, the following will hang:
```
./bin/driver read --model resent50 --enable-offload-copy
```
The reason it's hanging is because the argument parser is trying to spellcheck `--enable-offload-copy`. That uses the levenshtein distance algorithm to find the closest similar flag name, but looks like it's getting stuck in infinite recursion.

I was able to narrow down the flag where it's getting stuck, and it's comparing `--migraphx-json` with `--enable-offload-copy`.

**Comment by lakhinderwalia** [comment]
The first problem is, in runaction() the argument is actually taken as a file name -- the file is not found in the system, of course. Then the exception that is thrown is effectively being ignored. It shouldn't be. So let us first fix that, and see what more is needed.. 

BTW, after ignoring the exception, the spellcheck part is invoked in run_action()..

**Comment by lakhinderwalia** [comment]
_(After a small code change to intercept the runtime error ..)_

The command `./bin/driver read --model resent50 --enable-offload-copy` has now 3 scenarios to consider:

-  If exactly the above command is executed:
```
./bin/driver read --model resent50 --enable-offload-copy
error: Path does not exists: --enable-offload-copy
terminate called after throwing an instance of 'migraphx::version_1::exception'
  what():  /home/lakhindr/Latest/AMDMIGraphX/src/driver/main.cpp:301: load: Unknown model: resent50
Aborted (core dumped)
```

-  If the `resent50` is typed as `resnet50`, the command first prints an error: 
`the path does not exist: --enable-offload-copy`. 
And then goes on to dump a fairly long list of lines for presumably some resnet50 model.. 

- Even if the model option isn't given:
```
./bin/driver read  --enable-offload-copy
error: Path does not exists: --enable-offload-copy
Reading:
terminate called after throwing an instance of 'std::length_error'
  what():  cannot create std::vector larger than max_size()
Aborted (core dumped)
```

**Comment by pfultz2** [comment]
I do see three issues that do need to be fixed:

* Add validation for `--model` flag so we can catch an invalid model name during parse time instead of runtime
* Update `levenshtein_distance` algorithm on larger strings to use an O(n^2) algorithm
* If the argument starts with `-` print an error about non-existing flag when `levenshtein_distance` can't find a flag thats close instead of printing the error message from the exception(which is probably confusing).

**Comment by lakhinderwalia** [comment]
Thanks for pointing out the 3 issues. However, as you would see in the original bug description above, there is no exception message being printed. It just hangs (presumably in spellcheck..) 

The error messages that you see printed in my 3 cases (i.e. path does not exist..) is because it has to be printed upfront during (modified) exception handling. 

So, there likely is some change to the exception part.

**Comment by pfultz2** [comment]
> The error messages that you see printed in my 3 cases (i.e. path does not exist..) is because it has to be printed upfront during (modified) exception handling.

Printing it first bypasses the spellcheck. The spellcheck is the problem and should be fixed to not hang on long strings instead of bypassing it.
