### ISSUE TITLE
Split ref_ops_test into multiple files

### ISSUE THREAD

**Issue by pfultz2** [ROCmSoftwarePlatform/AMDMIGraphX#1943]
This sometimes takes forever to compile. We should split this across multiple files so it can compile in parallel.

EDIT:
The following ref tests under the `test` directory were moved to a separate `ref` directory:
```
ref_dot_op_test.cpp 
ref_loop_test.cpp
ref_ops_nonstd_shape_test.cpp
ref_ops_test.cpp
ref_rnn_ops_test.cpp
```
Following changes were made:
- Tests were stripped from `ref_ops_test.cpp` and `ref_ops_nonstd_shape_test.cpp`, and moved to separate files based on the type of operation. 
- Test cases having multiple tests were broken down to have a single test for each TEST_CASE.
- CMakeLists.txt file was added to `ref` directory; all the tests are compiled to a single executable.

**Comment by bpickrel** [comment]
All of the new ref test source files have a false include dependency on 
`#include <migraphx/onnx.hpp>`.  They should include `#include <migraphx/program.hpp>` instead.

**Comment by ahsan-ca** [comment]
> All of the new ref test source files have a false include dependency on `#include <migraphx/onnx.hpp>`. They should include `#include <migraphx/program.hpp>` instead.

Yeah, you are right; `onnx.hpp` includes `program.hpp` which is what we actually need.
Thanks for catching this, I did not realize it because the original `ref_ops_test.cpp` file only included `onnx.hpp` (although no test seems to have needed this).

I have used this opportunity to remove unnecessary includes from some other files as well (`loop.cpp`, `dot_op.cpp` and `rnn_ops.cpp`).

If you find anything else, please do let me know. Thanks again!

PR is up for review with the changes: https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/2175
