### ISSUE TITLE
Create rand_uniform operator to support Multinomial op

### ISSUE THREAD

**Issue by causten** [ROCmSoftwarePlatform/AMDMIGraphX#1958]
For the Multinomial op to be able to generate a distribution at runtime, a prerequisite is a `RandomSequence` operation that can generate random numbers on any target device.  The algorithm needs to be the same across devices to make results repeatable for verification testing.  (Currently, multinomial distributions are generated during Onnx parsing and the results loaded as `literal` instructions, but this won't work for dynamic input shapes.)

Multinomial and any other op. using the `RandomSequence` op would need to be able to accept a seed as an argument, to create a repeatable deterministic sequence for testing, and also a way to start with a random (clock-based) seed.  This needs to be able to be done at runtime.  

i.e. foo(shape, seed)
Consider using rocRand for GPU but make sure it uses a random algorithm we can implement everywhere

**Comment by bpickrel** [comment]
Began inquiries about feasibility with rocRand. Looks more complicated than it first seemed.

@RobsonRLemos of ML Libraries CAN reports (from contractors at Stream HPC) that  
> "This won't hold due to the ordering. We follow the same general algorithm [as cuRAND](https://docs.nvidia.com/cuda/curand/host-api-overview.html#host-api-overview): the output is generated from 8192 independent generators as subsequences in batches of 8 elements that are concatenated. Ordering is independent of hardware. None of the rocRAND generators have a STL counterpart that produce the same output since we need to handle parallelism: MT19937 from rocRAND/cuRAND will not produce the same sequence as std::uniform_real_distribution, std::mersenne_twister_engine.
Also important to note is that cuRAND and rocRAND skip different amounts of numbers between subsequences."
I think the last statement may refer to use of `std::discard_block_engine`

**Comment by bpickrel** [comment]
The name of the new operation will be rand_uniform.

**Comment by bpickrel** [comment]
The `rand_uniform` op. can't allocate a buffer for itself with the current engine features, because sizing it with a vector of dimensions attribute `output_lens` would lead to unbounded allocation sizes at compile time, which we don't support yet.  

Therefore, the `rand_uniform` op. will not allocate any buffers UFN; instead it will just populate a buffer that is passed to it.  @CharlieL7 or @pfultz2 will design an allocation op. for dynamic shape buffers separately, which will eventually provide the inputs for `rand_uniform`.
