### ISSUE TITLE
Pull request #199 appears to slow down alexnet, extra gpu::gemm ops?

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#200]
Performance of Alexnet batch size 64 slowed down with recent submission.

In particular, git hash 334b01c takes 13.88 seconds and git hash 8274cb7 takes 22.97 seconds.  The difference seems to be accounted for by "gpu::gemm" operations taking 10.46 seconds in the latter and being missing in the former.

Output from perf-onnx attached.

[alexnet-8274cb7.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/2932310/alexnet-8274cb7.txt)
[alexnet-334b01c.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/2932311/alexnet-334b01c.txt)

**Comment by scxiao** [comment]
In commit 334b01c, the loaded program added unnecessary identity at the end of the program as:
@40 = flatten[axis=1](@39) -> float_type, {64, 9216}, {9216, 1}
@41 = identity(@40) -> float_type, {64, 9216}, {9216, 1}
@42 = transpose[dims=1, 0](@5) -> float_type, {9216, 4096}, {1, 9216}
@43 = dot[alpha=1,beta=0](@41,@42) -> float_type, {64, 4096}, {4096, 1}
@44 = multibroadcast[output_lens=64, 4096](@43) -> float_type, {64, 4096}, {4096, 1}
@45 = multibroadcast[output_lens=64, 4096](@4) -> float_type, {64, 4096}, {0, 1}
@46 = add(@44,@45) -> float_type, {64, 4096}, {4096, 1}
@47 = relu(@46) -> float_type, {64, 4096}, {4096, 1}
@48 = identity(@47) -> float_type, {64, 4096}, {4096, 1}
@49 = transpose[dims=1, 0](@3) -> float_type, {4096, 4096}, {1, 4096}
@50 = dot[alpha=1,beta=0](@48,@49) -> float_type, {64, 4096}, {4096, 1}
@51 = multibroadcast[output_lens=64, 4096](@50) -> float_type, {64, 4096}, {4096, 1}
@52 = multibroadcast[output_lens=64, 4096](@2) -> float_type, {64, 4096}, {0, 1}
@53 = add(@51,@52) -> float_type, {64, 4096}, {4096, 1}
@54 = relu(@53) -> float_type, {64, 4096}, {4096, 1}
@55 = transpose[dims=1, 0](@1) -> float_type, {4096, 1000}, {1, 4096}
@56 = dot[alpha=1,beta=0](@54,@55) -> float_type, {64, 1000}, {1000, 1}
@57 = multibroadcast[output_lens=64, 1000](@56) -> float_type, {64, 1000}, {1000, 1}
@58 = multibroadcast[output_lens=64, 1000](@0) -> float_type, {64, 1000}, {0, 1}
@59 = add(@57,@58) -> float_type, {64, 1000}, {1000, 1}
@60 = identity(@40) -> float_type, {64, 9216}, {9216, 1}
@61 = identity(@47) -> float_type, {64, 4096}, {4096, 1}
But the actual output is @59.

Because of the identity operator, those gemm operators are removed by the dead_code_elimination. See the following program:

@37 = identity(@36) -> float_type, {64, 9216}, {9216, 1}
@38 = transpose[dims=1, 0](@1) -> float_type, {9216, 4096}, {1, 9216}
@39 = dot[alpha=1,beta=0](@37,@38) -> float_type, {64, 4096}, {4096, 1}
@40 = multibroadcast[output_lens=64, 4096](@39) -> float_type, {64, 4096}, {4096, 1}
@41 = multibroadcast[output_lens=64, 4096](@0) -> float_type, {64, 4096}, {0, 1}
@42 = add(@40,@41) -> float_type, {64, 4096}, {4096, 1}
@43 = relu(@42) -> float_type, {64, 4096}, {4096, 1}
@44 = identity(@43) -> float_type, {64, 4096}, {4096, 1}

In commit 8274cb4, the loaded program is:
@41 = identity(@40) -> float_type, {64, 9216}, {9216, 1}
@42 = transpose[dims=1, 0](@5) -> float_type, {9216, 4096}, {1, 9216}
@43 = dot[alpha=1,beta=0](@41,@42) -> float_type, {64, 4096}, {4096, 1}
@44 = multibroadcast[output_lens=64, 4096](@43) -> float_type, {64, 4096}, {4096, 1}
@45 = multibroadcast[output_lens=64, 4096](@4) -> float_type, {64, 4096}, {0, 1}
@46 = add(@44,@45) -> float_type, {64, 4096}, {4096, 1}
@47 = relu(@46) -> float_type, {64, 4096}, {4096, 1}
@48 = identity(@47) -> float_type, {64, 4096}, {4096, 1}
@49 = transpose[dims=1, 0](@3) -> float_type, {4096, 4096}, {1, 4096}
@50 = dot[alpha=1,beta=0](@48,@49) -> float_type, {64, 4096}, {4096, 1}
@51 = multibroadcast[output_lens=64, 4096](@50) -> float_type, {64, 4096}, {4096, 1}
@52 = multibroadcast[output_lens=64, 4096](@2) -> float_type, {64, 4096}, {0, 1}
@53 = add(@51,@52) -> float_type, {64, 4096}, {4096, 1}
@54 = relu(@53) -> float_type, {64, 4096}, {4096, 1}
@55 = transpose[dims=1, 0](@1) -> float_type, {4096, 1000}, {1, 4096}
@56 = dot[alpha=1,beta=0](@54,@55) -> float_type, {64, 1000}, {1000, 1}
@57 = multibroadcast[output_lens=64, 1000](@56) -> float_type, {64, 1000}, {1000, 1}
@58 = multibroadcast[output_lens=64, 1000](@0) -> float_type, {64, 1000}, {0, 1}
@59 = add(@57,@58) -> float_type, {64, 1000}, {1000, 1}

with @59 being the output, so gemm in the model is kept. 

As a conclusion, the slowdown comes from a bug in the previous commit, what removes code by mistake.
