### ISSUE TITLE
Memory related issues with scheduling

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#215]
Tried running performance tests with latest source (8b6a5cda3100ccbbd18cce5c89401751ec2cb128).

I see several issues that seem sensitive to having run the scheduling pass.  I've added a MIGRAPHX_DISABLE_SCHEDULING variable in my copy so I can easily trigger this functionality on/off:
1. On Vega 10 dpn92 batch 32 and fbresnet batch 32 deterministically fail with "bad alloc"
```
mev@chilecito:~/source/AMDMIGraphX/build/src/onnx$ ./perf_onnx /home/mev/source/migraphx_onnx/cadene/dpn92i32.onnx 
[libprotobuf INFO google/protobuf/io/coded_stream.cc:610] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 152000513
Compiling ... 
Allocating params ... 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```
This problem goes away compiling with a smaller batch size or disabling scheduling. It also doesn't occur on the Vega10 system.

2. My python driver script reports the following error for resnet50 batch size 64
```
memory not available to allocate buffer
```
But does not report this for smaller batch sizes. This problem occurs on Vega10 but not Vega20.

These failures are in addition to a
```
Workspace has changed during finalization.
```
message which came 6/38 times on Vega20 and 3/38 times on Vega10. These messages come from an expected issue in MIOpen 1.7.1.

Note: QA team is starting to test our product, so we may need a workaround so they don't run into these issues.

**Comment by mei-ye** [comment]
Paul's version of stream execution increases memory consumption dramatically.
Below shows dump after memory coloring pass using 128 batch size of resnet50.
Paul's version from develop branch:
scratch = @param:scratch -> float_type, {2434138112}, {1}

My version from stream_execution_checkin branch
scratch = @param:scratch -> float_type, {308281344}, {1}

Mev, you can compare it using your approach to query the system about available memory.

I notice that Paul remove my dominator computation and program analysis approach to compute memory conflicts due to stream execution.  Paul probably does not understand my approach.

**Comment by mei-ye** [comment]
People without optimization background do not understand dynamic program analysis is the cleanest approach.  Adding instructions to program to communicate results of program analysis are considered bad practice in compiler domain.

**Comment by mei-ye** [comment]
Also, I used my old checkout of "stream_execution_checkin" branch.  I don't know whether Paul changed this branch.  If yes,  you could use "stream_execution_develop" branch instead to compare.

**Comment by pfultz2** [comment]
I did change the way it computes memory conflicts by using merge points instead of split points as it would miss conflicts when there was multiple entry points.

I didnt use the dominator info with this new approach as I dont understand it enough right now to prove its correctness. Instead I focused on getting correctness over lowest memory at first since there was several subtle conflict and synchronization bugs already. 

I would like to add the dominator info back in when I can get some good test cases for it, and would be very happy to learn from Mei in more detail about how the dominator computation works and how it is used for memory conficts.

**Comment by mei-ye** [comment]
Memory consumption increases dramatically (7X for resnet50) because of Paul's change. 
I have never seen a multiple-entry program.  Multiple-exit programs are more common.
When you do program analysis, you apply gen and kill operations.  If you do not kill,  size of outstanding properties grows exponentially.  In this case, if you keep on accumulating live intervals at merge point, number of conflicts grows exponentially.

Dominator/Post-dominator are basic concepts in compiler.  It is used to identify gen and kill points. I worked on compiler for 20+ years and was once a global optimization coder reviewer for contributors from all companies.   In all of my previous works, I was trusted to do my work.  In this ream, my code and design can be removed silently, and I have to defend basic concepts and algorithms.

**Comment by scxiao** [comment]
This release we make the conflict table computation much faster then before (20x speedup). With this optimization, we can turn on the stream scheduling by default.

Additional work related to dominator to remove unnecessary conflicts is in issue #408
