### ISSUE TITLE
Quantization support

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#216]
Release v0.3 support for quantization.  One issue to track overall; add other issues as appropriate
- INT8 #139

**Comment by scxiao** [comment]
Implemented the following functionalities:
1. A function to convert all float_type instructions in a program to specified type (half_type or int8_type). Already verified its correctness and performance using the half_type (very close accuracy in various imagenet models and about 30% faster than float type). But we have another more general implementation that can handle more scenarios in item 2.
2. Implemented another function to covert one, or more, or all instructions of a program to a specific type. To implement the functionality in 1, we just need to for the conversion for all instruction, then wrote a pass to remove unnecessary conversions in the program.
3. Wrote a pass to remove all unnecessary conversion instructions as mentioned in item2.
4. Wrote a pass to adjust the output shape in hip memory allocation. The logic behand this we when do hip allocation, the shape is the output of contiguous shape, which is standard. Then later, after removing the contiguous, the actual output shape should be that of the instruction, and these shapes maybe different. If they are different, the output shape of the instruction will be incorrect since the output uses that of the hip allocation.  We wrote this pass to remove the mismatch. Please see a new issue

**Comment by scxiao** [comment]
A new issue #244 is created for the item 4 above.

**Comment by scxiao** [comment]
FP16 is working now. Accuracy is very close to fp32 and achieved about 30% performance improvement. 
INT8 is functionally working, accuracy is pretty close to fp32, but performance is bad because of lower functions.

**Comment by scxiao** [comment]
Close this issue and create issue #270 to track the int8 quantization.
