### ISSUE TITLE
Add more info on destination operands for instructions

### ISSUE THREAD

**Issue by kahmed10** [ROCmSoftwarePlatform/AMDMIGraphX#218]
PR #213 identified issues where dead code elimination removed instructions that were supposed to write to memory. Adding destination operands and checking for them in dead code elimination may fix this issue.

**Comment by pfultz2** [comment]
We already have a designated output, and we have an attribute to show which input argument was aliased in the output. 

We could extend DCE to compute a new graph of outputs based on output aliases, but it would need to understand memory overlapping as well. Otherwise it will be useless after memory coloring because everything(except the last instruction) aliases the same memory trunk. 

This of course would be more expensive then the current DCE pass.

**Comment by mei-ye** [comment]
For a program is like this:
@402 = gpu::gemm(@398,@400,@401)
@404 = hip::load_literal
@405 = multibroadcast[output_lens=128, 1000](@404)
@407 = gpu::add(@405,@405,output)

Since @402 is not read by any instructions, @402 is dead, and @398, @400, @401, and their transitive inputs are potentially dead as well.

This read/write reference should be explicitly represented in the program.  

DCE pass is a reversed IR walk, which can catch the transitive closure.  Existing DCE does a one-step look -ahead forward walk,  which can not catch the transitive closure.

**Comment by mei-ye** [comment]
In compiler, we present this program like:
t402 = gpu::gemm(t398,t400,t401)
t404 = hip::load_literal
t405 = multibroadcast t404
t407 = gpu::add(t405,t405,output)

where t402, t404 and etc. are temporary variables, which are destination and source operands of instructions.  These temporary variables can be mapped to register or memory, and participate in the data flow analysis.   No special treatment and awareness of pass ordering is needed in DCE and etc.

**Comment by mei-ye** [comment]
Multiple outputs can be represented as multiple destination operands:
t402, t403 = gpu:....

If you use compiler's approach, removal of an dead instruction does not need to remove the argument link from input() and output() vectors.  By the time data flow analysis reaches at this instruction, we know that t402 is dead, and if t402 is also dead, we can remove this instruction.   Current approach removes argument links when an instruction is removed, which could be risky since the order of inputs/outputs does have it semantic meaning for operators.

**Comment by pfultz2** [comment]
That is what is currently done(except we dont support multiple outputs). So maybe we should close this issue then?

> Current approach removes argument links when an instruction is removed, which could be risky since the order of inputs/outputs does have it semantic meaning for operators.

This is almost never done, because like you said its risky. We usually just replace the instruction, which causes the old instructions to become dead. DCE then only removes instructions that have no outputs, so there is no argument link that is ever removed.

**Comment by mei-ye** [comment]
If read/write relationship is represented explicitly and correctly, dead store elimination should be able to be called after any pass without being taught how to handle memory coloring.

Also,  current implementation can't handle transitive closure.   The algorithm is different from what compiler usually does.   I have dead stores from horizontal fusion that can't be removed by current DSE. 

Supporting machine learning software stack forces application and middle-ware developers to do compiler works without having compiler experience.

**Comment by pfultz2** [comment]
> If read/write relationship is represented explicitly and correctly, dead store elimination should be able to be called after any pass without being taught how to handle memory coloring.

Memory coloring is not needed, but checking for overlapping is needed. So when instruction A1 writes to offset of 0-7 and instructions A2 writes to offset of 8-15, and instruction B reads from offset 0-15 it can understand that instruction A1 and A2 is not dead code.

Currently, it is not implemented this way. Instead a read and write is associated if an instruction inputs uses an instruction's output. To make it work with the concat scenario, we insert an identity operator to associate the reads and writes in the program. And then at the end, `eliminate_identity` will get rid of these extra instructions.

> Also, current implementation can't handle transitive closure. The algorithm is different from what compiler usually does.

It does handle transitive closure. After it designates an instruction for dead code removal, it recursively inspects each of the instructions inputs [here](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/src/dead_code_elimination.cpp#L59) doing essentially a reverse IR walk.

> I have dead stores from horizontal fusion that can't be removed by current DSE.

If there are instructions that aren't being removed correctly please open an issue with a small test case, and I will look into fixing it. Of course, there are a few cases(such as instructions with an empty shape or the last instruction), we dont remove.

**Comment by mei-ye** [comment]
For your example, if instruction B reads from instruction A1 and A2,  an explicit read/write representation will be:
t1  = instruction A1   //  write t1
t2  = instruction A2   //  write t2
t3           = instruction B t1, t2  // read t1, t2 and write t3.
If instruction B is not dead, then instruction A1 and A2 are not dead as well.  It is nothing to do with where in the memory A1 and A2 are mapped to.

**Comment by pfultz2** [comment]
> For your example, if instruction B reads from instruction A1 and A2,

Instruction B technically only reads from instruction A1, but this overlaps with A2 so it cannot be removed. We could represent this overlap by having hidden arguments or changing the inputs to be `vector<vector<instruction_ref>>`.

Although this seems it would be more complicated when doing transformation as the hidden arguments need to be carried along. Instead we reify it as an instruction(using the `identity` operator), and then we remove these intermediate instruction at the end of the program.

**Comment by mvermeulen** [comment]
No change.
