### ISSUE TITLE
Documentation Install Issues

### ISSUE THREAD

**Issue by emerth** [ROCmSoftwarePlatform/AMDMIGraphX#705]
Platform: ROCM 3.10, Ubuntu 18.04.5, cmake 3.10.2

Install instructions issues:

- hcc has(?) been renamed to hipcc.
- cmake wants to see env var **CMAKE_CXX_COMPILER=/opt/rocm/bin/hipcc**, not merely **CXX=/opt/rocm/bin/hipcc**.
- rbuild instructions do not result in an "rbuild" command.
- dependency on nlohmann JSON C++ library is not met; generally will need nlohmann_json from https://github.com/nlohmann/json, and then prepend "CMAKE_PREFIX_PATH=/path/to/json/build" to the cmake invocation.
- dependency on msgpack is not met. Install all of Ubuntu's msgpack packages makes this go away.
- pybind11 from Ubuntu does not meet cmake's requirements. Perhaps rbuild would have installed an acceptable pybind11? That is, if rbuild worked. ie: cmake says: **Unknown CMake command "pybind11_strip".** 

 I do see the little repo for rbuild you link to but is has essentially the same instructions as this repo has for it's installation. Neither pip not pip3 result in an rbuild command line tool. Can you elaborate on this part?

**Comment by kahmed10** [comment]
Have you tried looking at the [Dockerfile](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/examples/Dockerfile.hip-clang) to see if you can replicate the installation? Aside from being a slightly older version of ROCm, the commands should work. Hip-clang (/opt/rocm/llvm/bin/clang++) is recommended instead of hcc with newer versions of ROCm.

Msgpack is a serialization format used by MIGraphX. The other dependencies can be imported when using rbuild. In your case, if rbuilt was installed successfully via pip, double check which directory your pip binaries are being installed to and add to your `PATH` environment variable appropriately.

**Comment by emerth** [comment]
> 
> 
> Have you tried looking at the [Dockerfile](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/examples/Dockerfile.hip-clang) to see if you can replicate the installation? 

Hmmm, OK. Can you tell me kahmed10 are you with AMD or are you just a ROCm user like me?

I ask because if you are with AMD and the answer is that I should reverse engineer the Docker installer, then I think I may have to go back to CUDA. OTOH if you're just another user like me, well, I suppose I should say thanks for the answer.

**Comment by kahmed10** [comment]
I agree with you that the instructions are dated, and we are working on overhauling our documentation before a v1.0 release. PR #672 is in flight and should add plenty of more examples and use cases. As of right now, the easiest way to get started is to use Docker, but that of course is not a solution for everyone.

With that said, we can keep this issue open and pivot it to address the problems you've encountered in our upcoming documentation overhaul.
