### ISSUE TITLE
migraphx/op/transpose.hpp:45: compute_shape: Permutation has wrong number of axes

### ISSUE THREAD

**Issue by cagery** [ROCmSoftwarePlatform/AMDMIGraphX#724]
When parsed by migraphx, through cpp_parse_load_save application, following models from ONNX Model Zoo show the given error:

- models/vision/classification/rcnn_ilsvrc13/model/rcnn-ilsvrc13-3.onnx
- models/vision/classification/alexnet/model/bvlcalexnet-3.onnx
- models/vision/classification/resnet/model/resnet50-caffe2-v1-3.onnx
- models/vision/classification/zfnet-512/model/zfnet512-3.onnx
- models/vision/classification/inception_and_googlenet/inception_v1/model/inception-v1-3.onnx
- models/vision/classification/inception_and_googlenet/inception_v2/model/inception-v2-3.onnx
- models/vision/classification/vgg/model/vgg19-caffe2-3.onnx
- models/vision/classification/caffenet/model/caffenet-6.onnx
- models/vision/classification/shufflenet/model/shufflenet-3.onnx

**Comment by mvermeulen** [comment]
@turneram try running models in ONNX runtime; depending on whether works we may obsolete or see how it is otherwise run.

**Comment by turneram** [comment]
After looking into it more, I think this is actually a slightly different issue hiding behind that error. In each of these models, there is a Pooling layer followed by a [Gemm](https://github.com/onnx/onnx/blob/master/docs/Operators.md#gemm). Input 'A' comes from the output of the pooling layer with a 4-d shape, and input 'B' is a 2-d literal that needs to be transposed (transB=1). This is what was leading to the 4-d permutation that was being fed into the transpose op for a 2-d tensor. Our implementation of Gemm uses the number of dimensions of args[0] ('A') to create the permutation when either transA or transB is non-zero, which shouldn't matter when 'A' and 'B' actually have the same dimensionality, but in this case was obfuscating the real issue.
In the versions of each of these models that run without the error, there is a reshape operator that reshapes the output of the pooling layer from 4-d to 2-d before the Gemm, which is why these versions don't see the same error. 
I'll submit an issue with ONNX to suggest adding this reshape op to these models, which should fix them, and see what they say.

**Comment by pfultz2** [comment]
> Our implementation of Gemm uses the number of dimensions of args[0] ('A') to create the permutation when either transA or transB is non-zero, which shouldn't matter when 'A' and 'B' actually have the same dimensionality, but in this case was obfuscating the real issue.

Since we support the Gemm using different ranks, then we should probably fix this bug.

> In the versions of each of these models that run without the error, there is a reshape operator that reshapes the output of the pooling layer from 4-d to 2-d before the Gemm

Hmm, the 4-d tensor is treated as a batch gemm so doing a reshape from 4d to 2d would change the result differently.

**Comment by mvermeulen** [comment]
@turneram updating to release 1.3; please assess what can be done for the GEMM case.

**Comment by causten** [comment]
ONNX upstream clams those models are no longer supported.  Will close
