### ISSUE TITLE
normalize_compute_shape: CONCAT: Non-axis dimensions should match

### ISSUE THREAD

**Issue by cagery** [ROCmSoftwarePlatform/AMDMIGraphX#752]
**Model from ONNX Zoo:** /models/vision/object_detection_segmentation/tiny-yolov3/model/tiny-yolov3-11.onnx 

```
MIGraphX Error: /cgMIGraphX/AMDMIGraphX/src/include/migraphx/op/concat.hpp:71: normalize_compute_shape: CONCAT: Non-axis dimensions should match
```

**Comment by scxiao** [comment]
Here is what I got:

```
================= node_op_type = Resize
inputs:
	leaky_relu: 	float_type, {1, 128, 1, 1}, {128, 1, 1, 1}
	@literal: 	float_type, {8}, {1}
	@literal: 	float_type, {4}, {1}

rio = 
0, 0, 0, 0, 1, 1, 1, 1, 
output:
	float_type, {1, 128, 2, 2}, {512, 4, 2, 1}

================= node_op_type = Concat
inputs:
	gather: 	float_type, {1, 128, 2, 2}, {512, 4, 2, 1}
	leaky_relu: 	float_type, {1, 256, 1, 1}, {256, 1, 1, 1}
```

Last two dimensions mismatch...

**Comment by scxiao** [comment]
The reason for the error is that the model contains dynamic input shapes, migraphx uses 1 as the default value, so the input size becomes {1, 3, 1, 1}. B the default value 1 is invalid for the input. 

I checked the input data contained in the msft test models, their input size is {1, 3, 416, 416}. After I use this shape for the dynamic shape value, this issue is gone. But we have another issue that:

```
AMDMIGraphX2/src/onnx/onnx_parser.cpp:385: parse_graph: Unknown operator: NonMaxSuppression
```
we do not have support for NonMaxSuppression operator.

**Comment by scxiao** [comment]
#866 is created to track the NonMaxSuppression operator, so close this issue.
